/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package aplikasiperpus;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Hp
 */
public class formPengembalian extends javax.swing.JFrame {
private Statement st;
private Connection con;
private ResultSet rspeminjaman;
private ResultSet rspengembalian;
private String pinjam, tempo, kembali;
private ResultSet rsbuku;
private ResultSet rsanggota;
private String tanggal="";
private String sql="";
private DefaultTableModel grid;
String nopen,nopin,iduser,idang;
int keterlambatan,jmlpinjam,denda;
    /** Creates new form formPengembalian */
    public formPengembalian() {
        initComponents();
        koneksiPengembalian();
        tampilPengembalian();
        waktu();
    }
    
    private void koneksiPengembalian(){
      try {
          Class.forName("com.mysql.jdbc.Driver");
          con=DriverManager.getConnection("jdbc:mysql://localhost:3306/visualperpustakaan","root","");
          //System.out.println("Koneksi Berhasil !!!");
          //JOptionPane.showMessageDialog(null, "Koneksi Berhasil");
        } catch (Exception e) {
          System.out.println("Gagal Koneksi"+e);
        }
    }
    
    private void tampilPengembalian(){
    Object[] Baris={"Kode Pengembalian","Kode Peminjaman","Tanggal Pengembalian","Telat/Hari"};
      grid =new DefaultTableModel(null, Baris);
      table_pengembalian.setModel(grid);
      String sql= "select * from pengembalian";
      try {
          java.sql.Statement stat = con.createStatement();
          ResultSet hasil= stat.executeQuery(sql);
            while (hasil.next()){
                String a = hasil.getString("kd_pengembalian");
                String b = hasil.getString("kd_peminjaman");
                String c = hasil.getString("tgl_kembali");
                String d = hasil.getString("telat");
                
                String[] data={a,b,c,d};
                grid.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null , "Gagal Tampil " +e);
        }
    }
    
    private void kosongkan(){
        kd_kembali.setText("");
        tcari.setText("");
        kd_anggota.setText("");
        jumlah.setText("");
        tkd2_kembali.setText("");
        telat.setText("");
        kd_kembali.requestFocus();
    }
    
    public void waktu(){        
        Date tgl=new Date();
        dpinjam.setDate(tgl);
        dtempo.setDate(tgl);
        dkembali.setDate(tgl);    
    }
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg11 = new aplikasiperpus.bg1();
        bg12 = new aplikasiperpus.bg1();
        jumlah = new javax.swing.JTextField();
        tkd2_kembali = new javax.swing.JTextField();
        dkembali = new com.toedter.calendar.JDateChooser();
        tcari = new javax.swing.JTextField();
        bcari_pinjam = new javax.swing.JButton();
        bupdate = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();
        bsave = new javax.swing.JButton();
        bcancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_pengembalian = new javax.swing.JTable();
        dtempo = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        telat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        kd_kembali = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        kd_anggota = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        dpinjam = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btelat = new javax.swing.JButton();

        javax.swing.GroupLayout bg11Layout = new javax.swing.GroupLayout(bg11);
        bg11.setLayout(bg11Layout);
        bg11Layout.setHorizontalGroup(
            bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        bg11Layout.setVerticalGroup(
            bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tkd2_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkd2_kembaliActionPerformed(evt);
            }
        });

        dkembali.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dkembaliPropertyChange(evt);
            }
        });

        tcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcariActionPerformed(evt);
            }
        });

        bcari_pinjam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bcari_pinjam.setText("Cari");
        bcari_pinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcari_pinjamActionPerformed(evt);
            }
        });

        bupdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bupdate.setText("Update");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });

        bdelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bdelete.setText("Delete");
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });

        bsave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bsave.setText("Save");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });

        bcancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bcancel.setText("Cancel");
        bcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelActionPerformed(evt);
            }
        });

        table_pengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_pengembalianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_pengembalian);

        dtempo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dtempoPropertyChange(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Telat");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Kode Pengembalian");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Kode Anggota");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Kode Buku");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel24.setText("Jumlah Pinjam");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tanggal Pinjam");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Jatuh Tempo");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Tanggal Pengembalian");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Cari Kode Pinjam");

        dpinjam.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dpinjamPropertyChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel1.setText("Form Pengembalian");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("/  Hari");

        btelat.setText("Hitung Telat");
        btelat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btelatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg12Layout = new javax.swing.GroupLayout(bg12);
        bg12.setLayout(bg12Layout);
        bg12Layout.setHorizontalGroup(
            bg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(269, 269, 269))
            .addGroup(bg12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(bg12Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(bg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg12Layout.createSequentialGroup()
                        .addComponent(bsave)
                        .addGap(18, 18, 18)
                        .addComponent(bupdate)
                        .addGap(18, 18, 18)
                        .addComponent(bdelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bcancel))
                    .addComponent(jLabel10)
                    .addGroup(bg12Layout.createSequentialGroup()
                        .addGroup(bg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addGap(36, 36, 36)
                        .addGroup(bg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(bg12Layout.createSequentialGroup()
                                .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bcari_pinjam))
                            .addComponent(kd_kembali)
                            .addComponent(kd_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4)
                    .addGroup(bg12Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(72, 72, 72)
                        .addGroup(bg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tkd2_kembali)
                            .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg12Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(bg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg12Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dtempo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(bg12Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(67, 67, 67)
                            .addComponent(dpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg12Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(bg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btelat)
                                .addComponent(dkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(bg12Layout.createSequentialGroup()
                                    .addComponent(telat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel12)))))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        bg12Layout.setVerticalGroup(
            bg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addGroup(bg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg12Layout.createSequentialGroup()
                        .addGroup(bg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(kd_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bcari_pinjam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bg12Layout.createSequentialGroup()
                                .addComponent(kd_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(bg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bg12Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(bg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(tkd2_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(bg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24)
                                            .addGroup(bg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(telat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel12))))
                                    .addGroup(bg12Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(btelat))))
                            .addComponent(jLabel2)))
                    .addGroup(bg12Layout.createSequentialGroup()
                        .addGroup(bg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bg12Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addGroup(bg12Layout.createSequentialGroup()
                                .addComponent(dpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dtempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addGroup(bg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(dkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(bg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bupdate)
                    .addComponent(bdelete)
                    .addComponent(bsave)
                    .addComponent(bcancel)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tkd2_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkd2_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tkd2_kembaliActionPerformed

    private void tcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcariActionPerformed

    private void bcari_pinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcari_pinjamActionPerformed
        // TODO add your handling code here:
        try {
            String sql="select * from peminjaman where kd_pinjam='"+ tcari.getText()+"'";
            st=con.createStatement();
            rspengembalian =st.executeQuery(sql);
            while (rspengembalian.next()) {
                String tp = rspengembalian.getString("tgl_pinjam");                
                java.util.Date tgl = new SimpleDateFormat("yyyy-MM-dd").parse(tp);
                dpinjam.setDate(tgl); 
                dpinjam.setEnabled(false);
                String kda = rspengembalian.getString("kd_anggota");
                kd_anggota.setText(kda);
                kd_anggota.setEnabled(false);
                String kdb = rspengembalian.getString("kd_buku");
                tkd2_kembali.setText(kdb);
                tkd2_kembali.setEnabled(false);
                String dp = rspengembalian.getString("tempo"); 
                java.util.Date tgl1 = new SimpleDateFormat("yyyy-MM-dd").parse(dp);
                dtempo.setDate(tgl1); 
                dtempo.setEnabled(false);
                String jmlh = rspengembalian.getString("jumlah");
                jumlah.setText(jmlh);
                jumlah.setEnabled(false);
            }            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bcari_pinjamActionPerformed

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
        // TODO add your handling code here:
        String sql= "insert into pengembalian values (?,?,?,?)";
        try{
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1,kd_kembali.getText());
            ps.setString(2,tcari.getText());
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            ps.setString(3,tanggal =format.format(dkembali.getDate()));
            ps.setString(4,telat.getText());
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosongkan();
            kd_kembali.requestFocus();
            tampilPengembalian();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+e);
        }
    }//GEN-LAST:event_bsaveActionPerformed

    private void table_pengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_pengembalianMouseClicked
        // TODO add your handling code here:
        int bar = table_pengembalian.getSelectedRow();
        String a = grid.getValueAt(bar, 0).toString();
        String b = grid.getValueAt(bar, 1).toString();
        String c = grid.getValueAt(bar, 2).toString();
        String d = grid.getValueAt(bar, 3).toString();

        kd_kembali.setText(a);
        tcari.setText(b);
        try{            
            java.util.Date tgl = new SimpleDateFormat("yyyy-MM-dd").parse(c);
            dkembali.setDate(tgl); 
        }catch(Exception m){}
        telat.setText(d);
    }//GEN-LAST:event_table_pengembalianMouseClicked

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        // TODO add your handling code here:
        String sql="update pengembalian set kd_peminjaman=?, tgl_kembali=?,telat=? where kd_pengembalian=?";
        try{
            PreparedStatement st= con.prepareStatement(sql);
            st.setString(1,tcari.getText());
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            st.setString(2,tanggal =format.format(dkembali.getDate()));
            st.setString(3,telat.getText());
            st.setString(4,kd_kembali.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate");
            kosongkan();
            kd_kembali.requestFocus();
            tampilPengembalian();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data gagal di Update");
        }
    }//GEN-LAST:event_bupdateActionPerformed

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null,"Hapus","Konfirmasi Dialog",JOptionPane.YES_NO_OPTION);
        if (ok==0) {
            try {
                String sql="delete from pengembalian where kd_pengembalian='"+ kd_kembali.getText() +"'";
                PreparedStatement st=con.prepareStatement(sql);
                st.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Berhasil Di Hapus");
                kosongkan();
                kd_kembali.requestFocus();
                tampilPengembalian();
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(null, "Tidak Ada Data Yang Di Hapus ....!! \n"
                    +e.getMessage());
            }
        }
    }//GEN-LAST:event_bdeleteActionPerformed

    private void bcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelActionPerformed
        // TODO add your handling code here:
        kosongkan();
        kd_anggota.setEnabled(true);
        tkd2_kembali.setEnabled(true);
        jumlah.setEnabled(true);
        dpinjam.setEnabled(true);
        dtempo.setEnabled(true);
    }//GEN-LAST:event_bcancelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
     new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String File =("src/Report/reportpengembalian.jasper");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/visualperpustakaan","root","");
            HashMap parameter = new HashMap();
            File report_buku = new File(File);
            Class.forName("com.mysql.jdbc.Driver");
            JasperReport jr = (JasperReport)JRLoader.loadObject(report_buku.getPath());
            JasperPrint jp = JasperFillManager.fillReport(jr, parameter, con);
            JasperViewer.viewReport(jp, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, "Data Tidak Dapat Di Cetak!"+e.getMessage(),"Cetak Data",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dpinjamPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dpinjamPropertyChange
        // TODO add your handling code here:
        if (dpinjam.getDate()!=null) {
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            pinjam =format.format(dpinjam.getDate());
        }
    }//GEN-LAST:event_dpinjamPropertyChange

    private void dtempoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dtempoPropertyChange
        // TODO add your handling code here:
        if (dtempo.getDate()!=null) {
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            tempo =format.format(dtempo.getDate());
        }
    }//GEN-LAST:event_dtempoPropertyChange

    private void dkembaliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dkembaliPropertyChange
        // TODO add your handling code here:
        if (dkembali.getDate()!=null) {
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            kembali =format.format(dkembali.getDate());
        }
    }//GEN-LAST:event_dkembaliPropertyChange

    private void btelatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btelatActionPerformed
        // TODO add your handling code here:
        try{
            DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            Date tanggalpinjam = format.parse(tempo);
            Date tanggalkembali = format.parse(kembali);
            long tanggalpinjam1 = tanggalpinjam.getTime();
            long tanggalkembali1 = tanggalkembali.getTime();
            long diff = tanggalkembali1 - tanggalpinjam1;
            long lama = diff / (24 * 60 * 60 * 1000);
            telat.setEnabled(false);
            telat.setText(Long.toString(lama)+"");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Gagal Hitung"+e);
        }
    }//GEN-LAST:event_btelatActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcancel;
    private javax.swing.JButton bcari_pinjam;
    private javax.swing.JButton bdelete;
    private aplikasiperpus.bg1 bg11;
    private aplikasiperpus.bg1 bg12;
    private javax.swing.JButton bsave;
    private javax.swing.JButton btelat;
    private javax.swing.JButton bupdate;
    private com.toedter.calendar.JDateChooser dkembali;
    private com.toedter.calendar.JDateChooser dpinjam;
    private com.toedter.calendar.JDateChooser dtempo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kd_anggota;
    private javax.swing.JTextField kd_kembali;
    private javax.swing.JTable table_pengembalian;
    private javax.swing.JTextField tcari;
    private javax.swing.JTextField telat;
    private javax.swing.JTextField tkd2_kembali;
    // End of variables declaration//GEN-END:variables

}
