/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasiperpus;
import java.io.File;
import java.sql.*;  
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Hp
 */
public class formAnggota extends javax.swing.JFrame {
    private Connection con;
    private String sql;
    private String tanggal="";
    DefaultTableModel grid =new DefaultTableModel();

    /**
     * Creates new form formAnggota
     */
    public formAnggota() {
        initComponents();        
        koneksiAnggota();
        tampilAnggota();
        tglditxt();
    }
    
    public void tglditxt(){
        //Date tgl=new Date();
        //DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
        //txttanggal.setDateFormatString(df.format(tgl));
        
        java.util.Date tgl=new java.util.Date();
        txttanggal.setDate(tgl);
    
    }
        
    private void koneksiAnggota(){
      try {
          Class.forName("com.mysql.jdbc.Driver");
          con=DriverManager.getConnection("jdbc:mysql://localhost:3306/visualperpustakaan","root","");
          //System.out.println("Berhasil Koneksi");
          //JOptionPane.showMessageDialog(null, "Koneksi Berhasil");
        }catch (Exception e) {
          System.out.println("Gagal Koneksi"+e);
        }
    }
    
    private void tampilAnggota(){
      Object[] Baris={"Kode Anggota","NIK","Nama Anggota","Tempat","Tanggal Lahir","Jenis Kelamin","Alamat"};
      grid =new DefaultTableModel(null, Baris);
      tableagt.setModel(grid);
      String sql= "select * from anggota ";
      try {
          java.sql.Statement stat = con.createStatement();
          ResultSet hasil= stat.executeQuery(sql);
            while (hasil.next()){
                String a = hasil.getString("kd_anggota");
                String b = hasil.getString("nik");
                String c = hasil.getString("nama");
                String d = hasil.getString("tempat");
                String e = hasil.getString("tgl_lahir");
                String f = hasil.getString("jk");
                String g = hasil.getString("alamat");
                
                
                String[] data={a,b,c,d,e,f,g};
                grid.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null , "Gagal Tampil " +e);
        }
    }
    
    private void kosongkan(){
        kd_anggota.setText("");
        tnik_anggota.setText("");
        tnma_anggota.setText("");
        ttl_anggota.setText("");
        rjk1_anggota.setSelected(true);
        talmt_anggota.setText("");
        tnik_anggota.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg11 = new aplikasiperpus.bg1();
        bsrc_anggota = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableagt = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bprint_anggota = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kd_anggota = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tnik_anggota = new javax.swing.JTextField();
        tnma_anggota = new javax.swing.JTextField();
        ttl_anggota = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rjk1_anggota = new javax.swing.JRadioButton();
        rjk2_anggota = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        talmt_anggota = new javax.swing.JTextArea();
        bupdt_anggota = new javax.swing.JButton();
        bdel_anggota = new javax.swing.JButton();
        bcan_anggota = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tsrc_anggota = new javax.swing.JTextField();
        txttanggal = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bsrc_anggota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bsrc_anggota.setText("Search");
        bsrc_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsrc_anggotaActionPerformed(evt);
            }
        });

        tableagt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableagt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableagtMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableagt);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 28)); // NOI18N
        jLabel1.setText("FORM ANGGOTA");

        bprint_anggota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bprint_anggota.setText("Print");
        bprint_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprint_anggotaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("NIK");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nama");

        save.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tempat / Tanggal Lahir");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Kode Anggota");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Alamat");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("/");

        rjk1_anggota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rjk1_anggota.setText("Laki-laki");

        rjk2_anggota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rjk2_anggota.setText("Perempuan");

        talmt_anggota.setColumns(20);
        talmt_anggota.setRows(5);
        jScrollPane1.setViewportView(talmt_anggota);

        bupdt_anggota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bupdt_anggota.setText("Update");
        bupdt_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdt_anggotaActionPerformed(evt);
            }
        });

        bdel_anggota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bdel_anggota.setText("Delete");
        bdel_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdel_anggotaActionPerformed(evt);
            }
        });

        bcan_anggota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bcan_anggota.setText("Cancel");
        bcan_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcan_anggotaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Kata Kunci Pencarian");

        tsrc_anggota.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tsrc_anggota.setText("Masukan Nama");
        tsrc_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsrc_anggotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg11Layout = new javax.swing.GroupLayout(bg11);
        bg11.setLayout(bg11Layout);
        bg11Layout.setHorizontalGroup(
            bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg11Layout.createSequentialGroup()
                .addGroup(bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg11Layout.createSequentialGroup()
                        .addGroup(bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bg11Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bg11Layout.createSequentialGroup()
                                        .addGroup(bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel9))
                                        .addGap(70, 70, 70))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg11Layout.createSequentialGroup()
                                        .addComponent(save)
                                        .addGap(18, 18, 18)
                                        .addComponent(bupdt_anggota)
                                        .addGap(18, 18, 18)))
                                .addGroup(bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bg11Layout.createSequentialGroup()
                                        .addComponent(rjk1_anggota)
                                        .addGap(18, 18, 18)
                                        .addComponent(rjk2_anggota))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tnik_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(bg11Layout.createSequentialGroup()
                                        .addComponent(bdel_anggota)
                                        .addGap(18, 18, 18)
                                        .addComponent(bcan_anggota)
                                        .addGap(27, 27, 27)
                                        .addComponent(bprint_anggota)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1))
                                    .addGroup(bg11Layout.createSequentialGroup()
                                        .addGap(285, 285, 285)
                                        .addComponent(bsrc_anggota))
                                    .addComponent(kd_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tnma_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(bg11Layout.createSequentialGroup()
                                        .addComponent(ttl_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(bg11Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(tsrc_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE))
                    .addGroup(bg11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(186, 186, 186))
        );
        bg11Layout.setVerticalGroup(
            bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bg11Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addGroup(bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kd_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tnik_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tnma_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ttl_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)))
                    .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rjk1_anggota)
                    .addComponent(rjk2_anggota)
                    .addComponent(jLabel5))
                .addGap(14, 14, 14)
                .addGroup(bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bupdt_anggota)
                    .addComponent(bdel_anggota)
                    .addComponent(bcan_anggota)
                    .addComponent(bprint_anggota)
                    .addComponent(save)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tsrc_anggota, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(bsrc_anggota)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txttanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txttanggalPropertyChange
        // TODO add your handling code here:
        if (txttanggal.getDate()!=null) {
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            tanggal =format.format(txttanggal.getDate());
        }
    }//GEN-LAST:event_txttanggalPropertyChange

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String sql= "insert into anggota values (?,?,?,?,?,?,?)";
        try{
            PreparedStatement st=con.prepareStatement(sql);
            st.setString(1,kd_anggota.getText());
            st.setString(2,tnik_anggota.getText());
            st.setString(3,tnma_anggota.getText());
            st.setString(4,ttl_anggota.getText());
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            st.setString(5, tanggal =format.format(txttanggal.getDate()));
            String jkel="";
            if(rjk1_anggota.isSelected()) jkel="Laki-Laki";
            else jkel="Perempuan";
            st.setString(6,jkel);
            st.setString(7,talmt_anggota.getText());            
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosongkan();
            tnik_anggota.requestFocus();
            tampilAnggota();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+ e);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void bupdt_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdt_anggotaActionPerformed
        // TODO add your handling code here:
        String sql="update anggota set nik=?, nama=?,tempat=?,tgl_lahir=?, jk=?,alamat=? where kd_anggota=?";
        try{
            PreparedStatement st= con.prepareStatement(sql);
            st.setString(1,tnik_anggota.getText());
            st.setString(2,tnma_anggota.getText());
            st.setString(3,ttl_anggota.getText());
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            st.setString(4, tanggal =format.format(txttanggal.getDate()));            
            String jkel="";
            if(rjk1_anggota.isSelected()) jkel="Laki-Laki";
            else jkel="Perempuan";
            st.setString(5,jkel);            
            st.setString(6,talmt_anggota.getText());            
            st.setString(7, kd_anggota.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate");
            kosongkan();
            tnik_anggota.requestFocus();
            tampilAnggota();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data gagal di Update"+e);
        }
    }//GEN-LAST:event_bupdt_anggotaActionPerformed

    private void tableagtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableagtMouseClicked
        // TODO add your handling code here:
        int bar = tableagt.getSelectedRow();
        String a = grid.getValueAt(bar, 0).toString();
        String b = grid.getValueAt(bar, 1).toString();
        String c = grid.getValueAt(bar, 2).toString();
        String d = grid.getValueAt(bar, 3).toString();
        String e = grid.getValueAt(bar, 4).toString();
        String f = grid.getValueAt(bar, 5).toString();
        String g = grid.getValueAt(bar, 6).toString();        
        kd_anggota.setText(a);
        tnik_anggota.setText(b);
        tnma_anggota.setText(c);        
        ttl_anggota.setText(d);
        try{            
            java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(e);
            txttanggal.setDate(date); 
        }catch(Exception m){}
        if(f.equals("Laki-Laki")){rjk1_anggota.setSelected(true); rjk2_anggota.setSelected(false);}
        else {rjk1_anggota.setSelected(false); rjk2_anggota.setSelected(true);}
        talmt_anggota.setText(g);
    }//GEN-LAST:event_tableagtMouseClicked

    private void bcan_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcan_anggotaActionPerformed
        kosongkan();
    }//GEN-LAST:event_bcan_anggotaActionPerformed

    private void bdel_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdel_anggotaActionPerformed
        int ok=JOptionPane.showConfirmDialog(null,"Hapus","Konfirmasi Dialog",JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0) {
            try {
                sql="delete from anggota  where kd_anggota='"+ kd_anggota.getText() +"'";
                PreparedStatement st=con.prepareStatement(sql);
                st.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Berhasil Di Hapus");
                kosongkan();
                kd_anggota.requestFocus();
                tampilAnggota();
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(null, "Tidak Ada Data Yang Di Hapus ....!! \n"
                    +e.getMessage());
            }
        }
    }//GEN-LAST:event_bdel_anggotaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bprint_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprint_anggotaActionPerformed
        // TODO add your handling code here:
        try{
            String File =("src/Report/reportanggota.jasper");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/visualperpustakaan","root","");
            HashMap parameter = new HashMap();
            File report_buku = new File(File);
            Class.forName("com.mysql.jdbc.Driver");
            JasperReport jr = (JasperReport)JRLoader.loadObject(report_buku.getPath());
            JasperPrint jp = JasperFillManager.fillReport(jr, parameter, con);
            JasperViewer.viewReport(jp, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, "Data Tidak Dapat Di Cetak!"+e.getMessage(),"Cetak Data",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bprint_anggotaActionPerformed

    private void bsrc_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsrc_anggotaActionPerformed
        // TODO add your handling code here:
        Object[] Baris={"Kode Anggota","NIK","Nama Anggota","Tempat","Tanggal Lahir","Jenis Kelamin","Alamat"};
        grid =new DefaultTableModel(null, Baris);
        tableagt.setModel(grid);
        String sql= "select * from anggota where nama like '%"+tsrc_anggota.getText()+"%' ";
        try {
            java.sql.Statement stat = con.createStatement();
            ResultSet hasil= stat.executeQuery(sql);
            while (hasil.next()){
                String a = hasil.getString("kd_anggota");
                String b = hasil.getString("nik");
                String c = hasil.getString("nama");
                String d = hasil.getString("tempat");
                String e = hasil.getString("tgl_lahir");
                String f = hasil.getString("jk");
                String g = hasil.getString("alamat");
                
                
                String[] data={a,b,c,d,e,f,g};
                grid.addRow(data);            
            }
        } catch (Exception e) {
              JOptionPane.showMessageDialog(null , "Gagal Tampil " +e);
        }
    }//GEN-LAST:event_bsrc_anggotaActionPerformed

    private void tsrc_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsrc_anggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsrc_anggotaActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formAnggota().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcan_anggota;
    private javax.swing.JButton bdel_anggota;
    private aplikasiperpus.bg1 bg11;
    private javax.swing.JButton bprint_anggota;
    private javax.swing.JButton bsrc_anggota;
    private javax.swing.JButton bupdt_anggota;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kd_anggota;
    private javax.swing.JRadioButton rjk1_anggota;
    private javax.swing.JRadioButton rjk2_anggota;
    private javax.swing.JButton save;
    private javax.swing.JTable tableagt;
    private javax.swing.JTextArea talmt_anggota;
    private javax.swing.JTextField tnik_anggota;
    private javax.swing.JTextField tnma_anggota;
    private javax.swing.JTextField tsrc_anggota;
    private javax.swing.JTextField ttl_anggota;
    private com.toedter.calendar.JDateChooser txttanggal;
    // End of variables declaration//GEN-END:variables
}